# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hardlopen
email: 
description: > # this means to ignore newlines until "baseurl:"
  Hardlopen van Eric Tummers. De wedstrijden en de tijden, maar vooral
  ook het plezier en de ervaring.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hardlopen.erictummers.nl" # the base hostname & protocol for your site
twitter_username: erictummers
github_username:  erictummers

# Build settings
markdown: kramdown
paginate: 5
gems: [jekyll-paginate]
excerpt_separator: "\n"